import type { Metadata } from "next";
import "./globals.css";
import { kanit } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="lg:cursor-none">
      <body className={`${kanit.className} antialiased `} data-theme="dark">
        {children}
      </body>
    </html>
  );
}
